musicstore-asp.net/MvcMusicStore/Backup/MvcMusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//添加命名空间
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        
        MusicStoreEntities storeDB = new MusicStoreEntities();
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new ShoppingCartViewModel 
            {
                CartItems=cart.GetCartItems(),
                CartTotal=cart.GetTotal()
            };
            return View(viewModel);
        }
        //将商品添加到购物车
        public ActionResult AddToCart(int id)
        {
            var addedAlbum = storeDB.Albums.Single(album=>album.AlbumId==id);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);
            return RedirectToAction("Index");
        }
        //将存在的商品从购物车中移除
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            string albumName = storeDB.Carts.Single(item=>item.RecondId==id).Album.Title;
            int itemCount = cart.RemoveFromCart(id);
            var results = new ShoppingCartRemoveViewModel 
            {
                Message=Server.HtmlEncode(albumName)+"已经从你的购物车中移除",
                CartTotal=cart.GetTotal(),
                CartCount=cart.GetCount(),
                ItemCount=itemCount,
                DeleteId=id
            };
            return Json(results);
        }

        //该操作作为子操作来进行
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

    }
}

musicstore-asp.net/MvcMusicStore/Backup/MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//添加命名空间
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        #region 注释掉的代码-这些都是测试用的
        //public string Index()
        //{
        //    return "你好-此页面来自Store.Index()";
        //}
        //封装一个操作方法的结果并用于代表该操作方法执行框架级操作。
        //public string Browse(string genre)
        //{
        //    //这里使用HttpUtility.HtmlEncode方法来处理用户的输入，这样可以防止用户的脚本注入攻击
        //    string message = HttpUtility.HtmlEncode("Store.Browse,genre="+genre);
        //    return message;
        //} 
        #endregion
        MusicStoreEntities storeDB = new MusicStoreEntities();
        public ActionResult Index()
        {
            #region 测试数据代码
            //var genres = new List<Genre>
            //{
            //    new Genre{Name="中国风"},
            //    new Genre{Name="伤感怀旧"},
            //    new Genre{Name="流行新曲"}
            //    return View(genres);
            //}; 
            #endregion
            var genres = storeDB.Genres.ToList();
            return View(genres);
        }

            #region 注释代码
        //public ActionResult Browse(string genre)
        //{
        //    var genreModel = new Genre { Name=genre};
        //    return View(genreModel);
        //} 
        #endregion
        public ActionResult Browse(string genre)
        {
            //获取专辑名称
            var genreModel = storeDB.Genres.Include("Albums").Single(g=>g.Name==genre);
            return View(genreModel);
        }
        //返回详细信息，但是这里返回没有啊，报错！！！ 在浏览器中重定向到store/details
        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);
            return View(album);
        }
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            //获取年代分类列表
            var genres = storeDB.Genres.ToList();
            //返回年代分类的列表，用于在视图中生成菜单
            return PartialView(genres);
        }
    }
}

musicstore-asp.net/MvcMusicStore/Backup/MvcMusicStore/Views/Store/Browse.cshtml
@model MvcMusicStore.Models.Genre

@{
    ViewBag.Title = "Browse";
}

<div class="genre">
    <h3><em>@Model.Name</em>专辑</h3>
    <ul id="album-list">
        @foreach (var album in Model.Albums)
        {
            <li>
                <a href="@Url.Action("Details",new { id=album.AlbumId })">
                    <img alt="@album.Title" src="@album.AlbumArtUrl" />
                    <span>@album.Title</span>
                </a>
            </li>
        }
    </ul>
</div>

musicstore-asp.net/MvcMusicStore/Backup/MvcMusicStore/Views/Store/Details.cshtml
@model MvcMusicStore.Models.Album   
           @*表示视图使用强类型的Album类 -Rozer视图引擎能够理解*@

@{
    ViewBag.Title = "Album-"+@Model.Title;
}

<h2>Album:@Model.Title</h2>
<p>
    <img alt="@Model.Title" src="@Model.AlbumArtUrl" />
</p>
<div id="album-details">
    <p>
        <em>年代:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>艺术家:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>价格:</em>
        @String.Format("{0:F}",Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("加入购物车", "AddToCart", "ShoppingCart", new{id=Model.AlbumId },"")
    </p>
</div>


musicstore-asp.net/MvcMusicStore/Backup/MvcMusicStore/Views/Store/GenreMenu.cshtml
@model IEnumerable<MvcMusicStore.Models.Genre>

@*显示年代分类信息*@
<ul id="categories">
       @foreach(var genre in Model)
       {
            <li>
                @Html.ActionLink(genre.Name, "Browse", "Store", new { Genre=genre.Name },null)
            </li>
       }
</ul>

musicstore-asp.net/MvcMusicStore/Backup/MvcMusicStore/Views/Store/Index.cshtml
@model IEnumerable<MvcMusicStore.Models.Genre>
@{
    ViewBag.Title = "Store";
}

<h3>Browse Genres</h3>
<p>
    Select from @Model.Count() genres:
</p>
<ul>
    @foreach (var genre in Model)
    { 
        <li>@Html.ActionLink(genre.Name, "Browse", new { genre=genre.Name})</li>
    }
</ul>
