musicstore-asp.net/MvcMusicStore/MvcMusicStore/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore.Models
{
    public class ShoppingCart
    {
        //创建上下文对象
        MusicStoreEntities storeDB = new MusicStoreEntities();
        //设置ShoppingCartId属性
        string ShoppingCartId { get; set; }
        //设置全局变量，用于记录CartId的值，这里好像是该表的主键
        public const string CartSessionKey = "CartId";
        //取得购物车
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        //登录之后的购物车CartId
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        //实现生成GetCartId
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] = context.User.Identity.Name;
                }
                else
                {
                    //生成全局唯一标识符作为CartId
                    Guid tempCartId = Guid.NewGuid();
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
        //添加到购物车
        public void AddToCart(Album album)
        {
            //购物车中是否存在该商品
            var cartItem = storeDB.Carts.SingleOrDefault(c=>c.CartId==ShoppingCartId&&c.AlbumId==album.AlbumId);
            if (cartItem == null)
            {
                cartItem = new Cart
                {
                    AlbumId = album.AlbumId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                storeDB.Carts.Add(cartItem);
            }
            else
            {
                cartItem.Count++;
            }
            storeDB.SaveChanges();
        }
        //将商品从购物车中移除
        public int RemoveFromCart(int id)
        {
            //判断购物车中是否存在该商品
            var cartItem = storeDB.Carts.Single(cart=>cart.CartId==ShoppingCartId&&cart.RecondId==id);
            int itemCount = 0;
            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    storeDB.Carts.Remove(cartItem);
                }
                storeDB.SaveChanges();
            }
            return itemCount;
        }
        //清空购物车
        public void EmptyCart()
        {
            var cartItems = storeDB.Carts.Where(cart => cart.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                storeDB.Carts.Remove(cartItem);
            }
            storeDB.SaveChanges();
        }
        //获取购物车中的详细信息
        public List<Cart> GetCartItems()
        {
            return storeDB.Carts.Where(cart=>cart.CartId==ShoppingCartId).ToList();
        }
        //获取购物数量
        public int GetCount()
        {
            int? count = (from cartItems in storeDB.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            return count ?? 0;
        }
        //获取总价
        public decimal GetTotal()
        {
            decimal? total = (from cartItems in storeDB.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count * cartItems.Album.Price).Sum();
            return total ?? decimal.Zero;
        }

        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;
            var cartItems = GetCartItems();
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail 
                {
                    AlbumId=item.AlbumId,
                    OrderId=order.OrderId,
                    UnitPrice=item.Album.Price,
                    Quantity=item.Count
                };
                orderTotal += (item.Count * item.Album.Price);
                storeDB.OrderDetail.Add(orderDetail);
            }
            order.Total = orderTotal;
            storeDB.SaveChanges();
            EmptyCart();
            return order.OrderId;
        }

        public void MigrateCart(string userName)
        {
            var shoppingCart = storeDB.Carts.Where(c=>c.CartId==ShoppingCartId);
            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            }
            storeDB.SaveChanges();
        }
    }
}

musicstore-asp.net/MvcMusicStore/MvcMusicStore/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//添加命名空间
using MvcMusicStore.Models;

namespace MvcMusicStore.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

musicstore-asp.net/MvcMusicStore/MvcMusicStore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//添加命名空间
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    //授权标注[Authorize]，用户在登录之后才能访问
    [Authorize]
    public class CheckoutController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        const string PromoCode = "FREE";
        //用来显示用户输入的信息表单
        public ActionResult AddressAndPayment()
        {
            return View();
        }

        //验证用户输入，处理订单
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection vaules)
        {
            var order = new Order();
            //更新模型实例
            TryUpdateModel(order);
            try
            {
                //在忽略大小写的情况下
                if (string.Equals(vaules["PromoCode"], PromoCode, StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.UserName = User.Identity.Name;
                    order.OrderDate = DateTime.Now;
                    //保存订单信息
                    storeDB.Order.Add(order);
                    storeDB.SaveChanges();
                    //处理订单
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);
                    return RedirectToAction("Complete", new { id=order.OrderId});
                }
            }
            catch
            {
                return View(order);
            }
        }

        //
        public ActionResult Complete(int id)
        {
            //检查当前订单是否属于当前用户
            bool isValid = storeDB.Order.Any(p=>p.OrderId==id&&User.Identity.Name==p.UserName);
            if (isValid)
            {
                return View(id);
            }
            else
            {
                //返回错误视图
                return View("Error");
            }
        }
    }
}

musicstore-asp.net/MvcMusicStore/MvcMusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//添加命名空间
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        
        MusicStoreEntities storeDB = new MusicStoreEntities();
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new ShoppingCartViewModel 
            {
                CartItems=cart.GetCartItems(),
                CartTotal=cart.GetTotal()
            };
            return View(viewModel);
        }
        //将商品添加到购物车
        public ActionResult AddToCart(int id)
        {
            var addedAlbum = storeDB.Albums.Single(album=>album.AlbumId==id);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);
            return RedirectToAction("Index");
        }
        //将存在的商品从购物车中移除
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            string albumName = storeDB.Carts.Single(item=>item.RecondId==id).Album.Title;
            int itemCount = cart.RemoveFromCart(id);
            var results = new ShoppingCartRemoveViewModel 
            {
                Message=Server.HtmlEncode(albumName)+"已经从你的购物车中移除",
                CartTotal=cart.GetTotal(),
                CartCount=cart.GetCount(),
                ItemCount=itemCount,
                DeleteId=id
            };
            return Json(results);
        }

        //该操作作为子操作来进行
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

    }
}

musicstore-asp.net/MvcMusicStore/MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//添加命名空间
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        #region 注释掉的代码-这些都是测试用的
        //public string Index()
        //{
        //    return "你好-此页面来自Store.Index()";
        //}
        //封装一个操作方法的结果并用于代表该操作方法执行框架级操作。
        //public string Browse(string genre)
        //{
        //    //这里使用HttpUtility.HtmlEncode方法来处理用户的输入，这样可以防止用户的脚本注入攻击
        //    string message = HttpUtility.HtmlEncode("Store.Browse,genre="+genre);
        //    return message;
        //} 
        #endregion
        MusicStoreEntities storeDB = new MusicStoreEntities();
        public ActionResult Index()
        {
            #region 测试数据代码
            //var genres = new List<Genre>
            //{
            //    new Genre{Name="中国风"},
            //    new Genre{Name="伤感怀旧"},
            //    new Genre{Name="流行新曲"}
            //    return View(genres);
            //}; 
            #endregion
            var genres = storeDB.Genres.ToList();
            return View(genres);
        }

            #region 注释代码
        //public ActionResult Browse(string genre)
        //{
        //    var genreModel = new Genre { Name=genre};
        //    return View(genreModel);
        //} 
        #endregion
        public ActionResult Browse(string genre)
        {
            //获取专辑名称
            var genreModel = storeDB.Genres.Include("Albums").Single(g=>g.Name==genre);
            return View(genreModel);
        }
        //返回详细信息，但是这里返回没有啊，报错！！！ 在浏览器中重定向到store/details
        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);
            return View(album);
        }
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            //获取年代分类列表
            var genres = storeDB.Genres.ToList();
            //返回年代分类的列表，用于在视图中生成菜单
            return PartialView(genres);
        }
    }
}

musicstore-asp.net/MvcMusicStore/MvcMusicStore/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("购物车("+ViewData["CartCount"]+")",
                "Index",
                "ShoppingCart",
                new {id="cart-status"})


musicstore-asp.net/MvcMusicStore/MvcMusicStore/Views/ShoppingCart/Index.cshtml
@model MvcMusicStore.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "购物车";
}
<script src="/Scripts/jquery-1.4.4.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");

            if (recordToDelete != '') {

                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }

                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });

    });


    function handleUpdate() {
        // Load and deserialize the returned JSON data
        var json = context.get_data();
        var data = Sys.Serialization.JavaScriptSerializer.deserialize(json);

        // Update the page elements
        if (data.ItemCount == 0) {
            $('#row-' + data.DeleteId).fadeOut('slow');
        } else {
            $('#item-count-' + data.DeleteId).text(data.ItemCount);
        }

        $('#cart-total').text(data.CartTotal);
        $('#update-message').text(data.Message);
        $('#cart-status').text('Cart (' + data.CartCount + ')');
    }
</script>
<h3>
    <em>Review</em> your cart:
</h3>
<p class="button">
    @Html.ActionLink("结账", "AddressAndPayment", "Checkout")
</p>
<div id="update-message">
</div>
<table>
    <tr>
        <th>
            歌曲名
        </th>
        <th>
            单价
        </th>
        <th>
            数量
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.CartItems)
    {
        <tr id="row-@item.RecondId">
            <td>
                @Html.ActionLink(item.Album.Title, "Details", "Store", new { id = item.AlbumId }, null)
            </td>
            <td>
                @item.Album.Price
            </td>
            <td id="item-count-@item.RecondId">
                @item.Count
            </td>
            <td>
                <a href="#" class="RemoveLink" data-id="@item.RecondId">Remove from cart</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            Total
        </td>
        <td>
        </td>
        <td>
        </td>
        <td id="cart-total">
            @Model.CartTotal
        </td>
    </tr>
</table>